version: "3.9"
services:
  frontend:
    build:
      context: ./front-end
      args:
        VITE_CUSTOMER_URL: "http://backend:8080/api/customers"
        VITE_AUTH_URL: "http://localhost:8081/account"
    ports:
      - "3000:80"
    depends_on:
      - backend
      - account-service

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ~/.gradle:/root/.gradle

  account-service:
    build: ./account-service
    ports:
      - "8081:8081"
    environment:
      - VITE_CUSTOMER_URL=http://backend:8080/api/customers
    depends_on:
      - backend